---
- hosts: 172.31.44.1
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present

  - name: install tree
    apt:
     name: tree
     statee: present
    ignore: yes
  - name: install wget
    apt:
     name: wget
     state: present